# create condaenv
# conda env create --name condaenv --file environment.yml

# update condaenv
# conda env update --prefix ./condaenv --file environment.yml  --prune

channels:
  - defaults
dependencies:
  - python=3.8
  - pip
  - pylint
  - pytest
  - regex
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - ipython
  - jupyterlab
  - black
